"""Methodology and Data Health — formulas, assumptions, data freshness."""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from dipdca.config import CACHE_DIR, FIXTURES_DIR, load_assets_config  # noqa: E402
from ui.components import page_header  # noqa: E402
from ui.theme import GLOBAL_CSS  # noqa: E402

st.set_page_config(
    page_title="Methodology & Data Health", page_icon="📋", layout="wide"
)
st.markdown(GLOBAL_CSS, unsafe_allow_html=True)
page_header("Methodology & Data Health", "Formulas, sources, freshness, and cache status.", "📋")

# --- Formulas ---
st.header("Core Formulas")

st.subheader("Total Return Index")
st.latex(r"TR_{base}(t) = \frac{AdjClose(t) \cdot FX(t)}{AdjClose(t_0) \cdot FX(t_0)}")
st.caption(
    "AdjClose: Yahoo Finance auto_adjust=True (dividend-reinvested). "
    "FX: ECB reference rates (units of base currency per EUR)."
)

st.subheader("Drawdown")
st.latex(r"DD(t) = \frac{P(t)}{\max_{s \leq t} P(s)} - 1")
st.caption("Signal uses prior completed close (t-1). Trade executes at t.")

st.subheader("XIRR")
st.latex(r"\sum_{i} \frac{CF_i}{(1+r)^{d_i/365}} = 0")
st.caption(
    "Solved via brentq (scipy). Investments are negative flows; terminal wealth is a positive flow."
)

st.subheader("Cash Interest Accrual")
st.latex(r"B(t) = B(t_0) \cdot (1 + r_{annual})^{d/365}")
st.caption("Day-by-day compounding using calendar days elapsed.")

st.subheader("Sharpe Ratio")
st.latex(r"Sharpe = \frac{\bar{r}_{excess}}{\sigma_{excess}} \cdot \sqrt{252}")

st.subheader("Sortino Ratio")
st.latex(r"Sortino = \frac{\bar{r}_{excess}}{\sigma_{downside}} \cdot \sqrt{252}")

# --- Lookahead Rules ---
st.header("No-Lookahead Rules")
st.markdown(
    """
    To prevent look-ahead bias:

    1. **Signal**: Drawdown is computed using the **prior completed close** (index t-1).
    2. **Execution**: Trade executes at the **next available close** (index t).
    3. **Contributions**: Cash arrives on payday, invested on the **next trading day**.
    4. **Tiers**: In tiered-dip, tiers reset only after a **new all-time high** is confirmed.
    """
)

# --- Data Sources ---
st.header("Data Sources")
st.markdown(
    """
    | Source | Data | Endpoint |
    |--------|------|----------|
    | Yahoo Finance (yfinance) | ETF/Index prices | `yf.Ticker.history(auto_adjust=True)` |
    | ECB Data Portal | EUR FX rates | `data-api.ecb.europa.eu/service/data/EXR/...` |
    | ECB Data Portal | EUR deposit rate | `data-api.ecb.europa.eu/service/data/FM/...` |
    | SNB | CHF policy rate | `data.snb.ch/api/cube/snbsnbzisratep/...` |
    | Synthetic Fixtures | Demo / offline | `data/fixtures/*.parquet` (generated by `generate.py`) |
    """
)

# --- Fixtures Status ---
st.header("Demo Fixtures Status")
fixture_files = {
    "bull_market.parquet": "5yr bull market (synthetic GBM, mu=12%, sigma=15%)",
    "crash_and_recovery.parquet": "Bull → 40% crash → recovery (synthetic)",
    "sideways.parquet": "5yr sideways (synthetic GBM, mu=2%, sigma=20%)",
    "demo_fx.parquet": "Stable FX (EUR/USD/CHF, synthetic mean-reverting)",
}

fixture_rows = []
for filename, description in fixture_files.items():
    path = FIXTURES_DIR / filename
    exists = path.exists()
    size_kb = f"{path.stat().st_size / 1024:.1f} KB" if exists else "—"
    last_mod = (
        pd.Timestamp(path.stat().st_mtime, unit="s").strftime("%Y-%m-%d %H:%M")
        if exists
        else "—"
    )
    fixture_rows.append(
        {
            "File": filename,
            "Description": description,
            "Exists": "Yes" if exists else "No — run generate.py",
            "Size": size_kb,
            "Generated": last_mod,
        }
    )

st.dataframe(pd.DataFrame(fixture_rows), use_container_width=True, hide_index=True)

if not all((FIXTURES_DIR / f).exists() for f in fixture_files):
    st.warning(
        "Some fixtures are missing. Run: `uv run python data/fixtures/generate.py`",
        icon="⚠️",
    )

# --- Cache Status ---
st.header("Price Cache Status")
db_path = CACHE_DIR / "prices.duckdb"
if db_path.exists():
    size_mb = db_path.stat().st_size / 1024 / 1024
    st.success(f"Cache database exists ({size_mb:.2f} MB): {db_path}")
    try:
        import duckdb

        conn = duckdb.connect(str(db_path))
        symbols = conn.execute(
            "SELECT symbol, COUNT(*) as n_rows, MAX(dt) as last_dt FROM price_cache GROUP BY symbol ORDER BY symbol"
        ).df()
        conn.close()
        if len(symbols) > 0:
            st.dataframe(symbols, use_container_width=True, hide_index=True)
        else:
            st.info("Cache is empty — data will be fetched on demand.")
    except Exception:
        st.info("Cache database exists but could not be read.")
else:
    st.info("No cache database yet — it will be created when you first load live data.")

# --- Asset Universe ---
st.header("Asset Universe")
assets = load_assets_config()
asset_df = pd.DataFrame(
    [
        {
            "ID": a["id"],
            "Name": a["display_name"],
            "Index": a.get("index_symbol") or "—",
            "ETF": a["etf_symbol"],
            "Currency": a["quote_currency"],
            "Category": a.get("category", ""),
        }
        for a in assets
    ]
)
st.dataframe(asset_df, use_container_width=True, hide_index=True)

# --- Limitations ---
st.header("Known Limitations")
st.markdown(
    """
    - **Slippage model is flat**: real slippage varies by liquidity and order size.
    - **Tax treatment is simplified**: no wash-sale rules, no tax-loss harvesting.
    - **No dividend recapture timing**: assumes dividends are immediately reinvested.
    - **No bid/ask spread**: uses close prices only.
    - **Survivorship bias**: historical ETF data reflects funds that still exist.
    - **Demo data is synthetic**: GBM is not representative of real market dynamics.
    - **FX rates are spot rates**: actual ETF FX exposure may differ (hedging, settlement).
    """
)

st.caption(
    "This tool is for educational purposes only. Not investment advice. "
    "See DISCLAIMER.md for full terms."
)
