[theme]
base = "dark"
primaryColor = "#42E8FF"
backgroundColor = "#07070A"
secondaryBackgroundColor = "#111218"
textColor = "#F7F7F2"
font = "sans serif"

[server]
headless = true
port = 8501

[client]
showErrorDetails = false
